
volumes:
  postgres-data:
    driver: local
  server-data:
    driver: local

services:
    postgres:
        image: postgres:14-alpine
        restart: unless-stopped
        ports:
          - ${DATABASE_POSTGRES_PORT}:5432 # for local development
        volumes:
          - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DATABASE_POSTGRES_USER}
            POSTGRES_PASSWORD: ${DATABASE_POSTGRES_PASSWORD}
            POSTGRES_DB: ${DATABASE_POSTGRES_DB}
    redis:
        image: redis:6.2-alpine
        restart: unless-stopped
    dashboard:
        image: wembat-dashboard
        build:
            context: .
            dockerfile: ./workspaces/dashboard/Dockerfile        
        restart: unless-stopped
        logging:
          driver: none
        ports:
            - ${DASHBOARD_SERVER_PORT}:8080
    server:
        image: wembat-server
        build:
            context: .
            dockerfile: ./workspaces/server/Dockerfile
        restart: unless-stopped
        ports:
            - ${API_SERVER_PORT}:8080
            - 5555:5555 # for local development
        volumes:
            - server-data:/opt/data
        environment:
            SERVER_URL: ${API_SERVER_URL}
            DATABASE_URL: ${API_DATABASE_URL}
            DATABASE_HOST: postgres
            DATABASE_USER: ${DATABASE_POSTGRES_USER}
            DASHBOARD_URL: ${DASHBOARD_SERVER_URL}
            REDIS_HOST: redis
            REDIS_PORT: 6379