
volumes:
  postgres-data:
    driver: local
  server-data:
    driver: local

services:
    postgres:
        image: postgres:14-alpine
        healthcheck:
            test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
            interval: 5s
            timeout: 1s
            retries: 5
        restart: unless-stopped
        ports:
          - ${DATABASE_PORT}:5432 # for local development
        volumes:
          - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_DB}
    redis:
        image: redis:6.2-alpine
        restart: unless-stopped
        ports:
          - ${REDIS_PORT}:6379 # for local development

    dashboard:
        image: wembat-dashboard
        build:
            context: .
            dockerfile: ./workspaces/dashboard/Dockerfile
        restart: unless-stopped
        logging:
          driver: none
        ports:
            - ${DASHBOARD_PORT}:8080

    server:
        image: wembat-server
        build:
            context: .
            dockerfile: ./workspaces/server/Dockerfile
        depends_on:
            postgres:
                condition: service_healthy
        restart: unless-stopped
        ports:
            - ${SERVER_PORT}:8080
            - 5555:5555 # for local development
        volumes:
            - server-data:/opt/data
        environment:
            SERVER_HOST: ${SERVER_HOST}
            SERVER_PORT: ${SERVER_PORT}
            DASHBOARD_HOST: ${DASHBOARD_HOST}
            DASHBOARD_PORT: ${DASHBOARD_PORT}
            REDIS_PORT: ${REDIS_PORT}
            REDIS_HOST: ${REDIS_HOST}
            DATABASE_USER: ${DATABASE_USER}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_DB: ${DATABASE_DB}
            DATABASE_HOST: ${DATABASE_HOST}
            DATABASE_PORT: ${DATABASE_PORT}