
volumes:
  postgres-data:
    driver: local

services:
    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: PLACEHOLDER_POSTGRES_USER
            POSTGRES_PASSWORD: PLACEHOLDER_POSTGRES_PASSWORD
            POSTGRES_DB: PLACEHOLDER_POSTGRES_DB
        volumes:
          - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped
    redis:
        image: redis:6.2-alpine
        restart: unless-stopped
    api:
        image: wembat-api
        build: "./"
        restart: unless-stopped
        ports:
            - 8080:8080
            - 5555:5555
        environment:
            - "API_PORT=${API_PORT}"
            - "API_URL=${API_URL}"
            - "DATABASE_URL=${API_DATABASE_URL}"
            - "REDIS_HOST=redis"
            - "REDIS_PORT=6379"
            - "APP_DOMAINS=${APP_DOMAINS}"