version: "3.7"

volumes:
  postgres-data:
    driver: local

services:
    postgres:
        image: postgres
        hostname: postgres
        ports:
        - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: testdb
        volumes:
          - postgres-data:/var/lib/postgresql/data
        restart: unless-stopped
    redis:
        image: redis:6.2-alpine
        ports:
            - 6379:6379    
    api:
        image: wembat-api
        build: "./"
        restart: always
        command: ""
        ports:
            - 8080:8080
            - 5555:5555
        environment:
            - "RPID=localhost"
            - "PORT=${API_PORT}"
            - "DATABASE_URL=${API_DATABASE_URL}"
            - "REDIS_HOST=redis"
            - "REDIS_PORT=6379"