name: test-frontend

on: [push]

jobs:
  test-wembat-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./src"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx vitest ./src/funtions/